### ISSUE TITLE
Audit and clean the .env key inventory on both hosts (Mac + VPS)

### ISSUE THREAD

**Issue by kamilpajak** [kamilpajak/AlphaLens#1101]
## Problem

The env-key inventory has drifted across hosts and no one has reconciled it against actual consumers:

- Mac: `.env` at the repo root (developer copy).
- VPS: `/etc/alphalens/env` (systemd units) plus whatever the Docker stacks inject.
- CLAUDE.md already names two DEAD keys still present in live copies: `GOOGLE_API_KEY` (Gemini client removed, PR #416) and `ALPACA_*` (paper-trade + broker chain decommissioned, ADR 0012).
- Research-only tier (`SIMFIN_API_KEY`, `QUIVER_API_KEY`, `IVOLATILITY_API_KEY`, `RUNPOD_API_KEY`) may include expired subscriptions.
- `.env.example` is the documented catalogue - it may also list keys with zero source consumers by now.

## Goal

One reconciled inventory: every key in every copy either has a named consumer in the source tree or is deleted. `.env.example` matches reality.

## How (suggested)

1. Enumerate keys per host (`.env` on Mac, `/etc/alphalens/env` + compose env on VPS) - names only, never values.
2. For each key, grep the source tree for consumers (os.environ / from_env / settings); classify live / research-only / dead.
3. Delete dead keys from both hosts and from `.env.example`; note removals in the PR body.
4. Verify after: one full nightly cycle on the VPS (thematic-build, feedback, edgar, broker-manager) with no missing-env errors in the journals.

## Notes

- Never print or log secret VALUES anywhere in this work - key names only.
- Config-from-env goes through `from_env()` only (existing doctrine) - any key read some other way is a finding of its own.

Wake: 2026-09-05

**Comment by kamilpajak** [comment]
Add to the audit scope (found 2026-08-24 while fixing the Grafana dashboard):

- `~/monitoring/docker-compose.yml` on the VPS sets `GF_SECURITY_ADMIN_PASSWORD=secure_password` (a placeholder). The RUNNING Grafana does not accept it - Grafana persists the first-init admin credentials in the `monitoring_grafana_data` volume, so the compose env value is dead configuration that misleads an operator. Either align the env var with reality or remove it with a comment.
- Grafana provisioning on the VPS (`~/monitoring/grafana/provisioning/{datasources,dashboards}`) is NOT versioned in the repo - only the dashboard JSON is (`deploy/monitoring/grafana/dashboards/`). The datasource yml drifted (missing `uid: prometheus`, fixed by hand 2026-08-24) and the dashboard copy was 2+ months stale. Same drift class the Prometheus rules had before #1073.

**Comment by kamilpajak** [comment]
## Audit executed 2026-09-04 (key NAMES only; values never read or printed)

### Per-host actions

**Mac `.env`** (backup kept outside the repo, `chmod 600`):
- Deleted: `GOOGLE_API_KEY`, `ALPACA_API_BASE_URL`, `ALPACA_API_KEY`, `ALPACA_API_SECRET`, `ALPACA_TEST_API_KEY`, `ALPACA_TEST_API_SECRET` (documented DEAD tiers) + `SIMFIN_API_KEY`, `QUIVER_API_KEY` (new finding: zero source consumers anywhere in the tree — both subscriptions expired).
- Kept: the live tier, plus `IVOLATILITY_API_KEY` (consumers: `backfill_ivolatility_pre_2018.py`, `pull_ivolatility_*.py`) and `RUNPOD_API_KEY` (runpod operator tooling outside the repo) as research-only.

**VPS `/etc/alphalens/env`** (backup at `/etc/alphalens/env.bak-2026-09-04`):
- `GOOGLE_API_KEY` / `ALPACA_*` were already absent (partly resolved before this audit).
- Deleted: `SIMFIN_API_KEY`, `QUIVER_API_KEY` (dead everywhere), `IVOLATILITY_API_KEY`, `RUNPOD_API_KEY` (no VPS-side consumer; verified zero references in `~/.config/systemd/user/` and `deploy/systemd/`).
- Kept: live tier + `GH_TOKEN` (literature publish), `ALPHALENS_TEXTFILE_DIR`, `SAXO_*`, `SAXO_ENV`, `ALPHALENS_OPENROUTER_QUANTIZATIONS`.

**Grafana** (`~/monitoring/docker-compose.yml`, backup beside it): removed the dead `GF_SECURITY_ADMIN_PASSWORD` placeholder, replaced with a comment (Grafana reads first-init admin credentials from the `monitoring_grafana_data` volume, so the env value was dead configuration). The second bullet of the 2026-08-24 comment (unversioned Grafana provisioning) was already resolved by #1111 — `deploy/monitoring/grafana/provisioning/` is in the repo and mounted on the VPS.

**Repo:** PR #1311 moves `SIMFIN_API_KEY` + `QUIVER_API_KEY` to the DEAD block in `.env.example` and pins the invariant that a DEAD key can never be an active `KEY=` line.

### Smoke verification (same day)
- `alphalens-broker-manager` restarted clean (daemon re-read the trimmed env; ticks and reconcile normal).
- `alphalens-edgar-detect` and `alphalens-saxo-refresh` fired clean.
- No missing-env errors in any journal.

### Findings: keys read outside `from_env()` (reported, not fixed here)
1. CLI command bodies read `POLYGON_API_KEY` / `OPENROUTER_API_KEY` / `PERPLEXITY_API_KEY` raw (`thematic.py`, `buffett.py`, `literature.py`) instead of the vendor clients' `from_env()`.
2. The `TELEGRAM_BOT_TOKEN` / `TELEGRAM_CHAT_ID` pair is read raw in 5 files with no owner module or name constant.
3. `SEC_EDGAR_USER_AGENT` has two independent constant definitions with separate default UAs (`sec_edgar_client.py`, `edgar_fundamentals.py`).
4. Research scripts use an uncatalogued `ALPHALENS_IVOL_API_KEY` / `IVOL_API_KEY` fallback pair.
5. The broker/automanager layer reads env at call time BY DESIGN (documented in `state_paths.py` / `entry_trails.py`) — not a violation.

Each of 1-4 is a candidate for its own small issue if considered worth fixing.

### Remaining verification
One full nightly cycle (thematic-build 20:30 UTC today + feedback-shadow-returns 06:30 UTC tomorrow) must show no missing-env errors — hence the `Wake: 2026-09-05` below (date = the first morning after the full cycle).

**Comment by kamilpajak** [comment]
## Overnight verification passed — closing

The issue's "done when" was one full nightly cycle with no missing-env errors. That cycle has now run with the trimmed `/etc/alphalens/env`:

| unit | last run (CEST) | env errors since the edit |
|---|---|---|
| `alphalens-thematic-build` | 2026-09-05 06:32 | 0 |
| `alphalens-feedback-shadow-returns` | 2026-09-05 08:30 | 0 |
| `alphalens-edgar-detect` | 2026-09-05 09:30 | 0 |
| `alphalens-saxo-refresh` | 2026-09-05 09:40 | 0 |
| `alphalens-grouped-daily-topup` | 2026-09-05 03:30 | 0 |
| `alphalens-edge-mirror` | 2026-09-05 09:34 | 0 |
| `alphalens-broker-manager` (daemon) | restarted 2026-09-04 | 0 |
| `alphalens-issue-wake` | — | 0 |

Scan window starts at the edit (2026-09-04 14:00 UTC) and matches missing-key / unset-environment-variable shapes.

**One failure in the window, proven unrelated:** `alphalens-form4-incremental` failed on 2026-09-05 with `ArrowTypeError: Unable to merge: Field issuer_cik has incompatible types: string vs large_string` — a parquet schema regression from PR #82, tracked and fixed in #1329 / PR #1331. Its env error count is 0 and `SEC_EDGAR_USER_AGENT`, the only key it needs, was never touched.

**Residual gap, stated rather than hidden:** the weekly and monthly literature-scan units have not fired since the edit (weekly runs Sunday, monthly on the 1st). They were verified by source instead of by a run: their code path reads only `PERPLEXITY_API_KEY` and `TELEGRAM_BOT_TOKEN`/`TELEGRAM_CHAT_ID`, and the publish wrapper uses `GH_TOKEN` — all four kept. No removed key appears anywhere in that path.

Repo half landed in PR #1311; the tier table was corrected in PR #1313.
